stages:
  - test

.test:
  image: node:12
  stage: test
  before_script:
    #- apt-get update
    #- apt-get install -y git
    - npm i --cache .npm --prefer-offline --no-audit --progress=false nyc codecov protoc grpc-tools
    - npm i --cache .npm --prefer-offline --no-audit --progress=false
    - git submodule update --init --recursive

compile typescript:
  stage: test
  extends: .test
  script:
    - npm run build

run tests:
  stage: test
  extends: .test
  script:
    - ./node_modules/nyc/bin/nyc.js npm test

code coverage:
  stage: test
  extends: .test
  script:
    - ./node_modules/nyc/bin/nyc.js report --reporter=text-lcov
